CREATE DATABASE customer_behaviour;
USE customer_behaviour;

ALTER TABLE df RENAME TO customers;

-- what is the total revenu generated by  male vs female customers'
select gender , sum(purchase_amount) revenue from customers group by gender;

-- which customers used a discount but still spent more the average purchase amount?
select	* from customers where discount_applied = 'Yes'and purchase_amount > (select avg(purchase_amount) from customers );


-- which are the top 5 product with the highest avg review rating?
select item_purchased,avg(review_rating) 'Review' from customers group by 1 order by 2 desc limit 5;
-- Compare the average purchase amounts between standard and express shipping?
select shipping_type,Round(avg(purchase_amount),2) from customers where shipping_type in ('Express','Standard') group by 1;

-- Do suscribed customers spend more ? Compareaverage spend and total revenue between suscribe and non-suscribe;
select subscription_status, count(customer_id) total_customer ,avg(purchase_amount) avgSpend ,sum(purchase_amount) totalRevenue from 
customers group by 1;
 
 -- which 5 product have the highest percentage of purchase with discounts applied?
 select item_purchased,count(item_purchased) purchase_time from customers where discount_applied='Yes' group by 1 order by 2 desc limit 5;
 
 select item_purchased,
 round(100* sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_rate 
 from customers
 group by item_purchased
 order by  discount_rate desc limit 5;
 
 -- segment customers into New, Returning, and Loyal based on their 
 -- total number of previous purchases, and show the count of each segment?
 
with customer_type as (
select customer_id,previous_purchases,
case
	when previous_purchases= 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
from customers
            )
select customer_segment, count(*) as 'Number of Customers'
from customer_type
group by customer_segment;

-- what are the top 3 most purchased products within each category?

select * from (
select category,item_purchased,count(item_purchased) PTime,
row_number() over(partition by category order by category,count(item_purchased)  desc) Crank
from customers  group by 1,2 ) t
where crank<=3;

-- are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select customer_id,previous_purchases
from customers where previous_purchases>5 and  subscription_status='yes';

-- what is the revenue contribution of each age group?
select age_group,sum(purchase_amount) from customers group by 1;